[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# INDEX
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/index"
  status = 200

# TOOLS — RFWeb2APK (3 fungsi)
[[redirects]]
  from = "/tools/rfweb2apk-url"
  to = "/.netlify/functions/rfweb2apk-url"
  status = 200

[[redirects]]
  from = "/tools/rfweb2apk-zip"
  to = "/.netlify/functions/rfweb2apk-zip"
  status = 200

[[redirects]]
  from = "/tools/rfweb2apk-html"
  to = "/.netlify/functions/rfweb2apk-html"
  status = 200

# PREMIUM — Alight Motion
[[redirects]]
  from = "/premium/am-send"
  to = "/.netlify/functions/am-send"
  status = 200

[[redirects]]
  from = "/premium/am-verify"
  to = "/.netlify/functions/am-verify"
  status = 200

[[redirects]]
  from = "/premium/am-refresh"
  to = "/.netlify/functions/am-refresh"
  status = 200

[[redirects]]
  from = "/premium/am-status"
  to = "/.netlify/functions/am-status"
  status = 200

# SPA FALLBACK
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
